spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/interview_management}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=InterviewManagementSystem@2026$JWT#Secret!Railway123456789
jwt.expiration=86400000

spring.mvc.log-request-details=true
logging.level.org.springframework.web=DEBUG